name: musios.app
title: musios.app
tab_title: "musios.app: a collection of tools for music creators and performers"
description: A collection of tools for music creators and performers

domain: musios.app
url: "https://musios.app"
baseurl: "/"

author:
  name: Andrew Hunt (musios)
  site: http://musios.app

title_separator: "-"

lang: en

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - kramdown-parser-gfm
  - jekyll-seo-tag

theme: minima
markdown: kramdown

show_dir_listing: false

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

defaults:
  - scope:
      path: "" # means all files in the project
    values:
      layout: "default"

projects_homes:
  - dir: "/projects/support-act"
    home: "index.html"
  - dir: "/projects/spotify-playlist-to-gigperformer"
    home: "README.md"
  - dir: "/projects/numaxpiano-midi-controller"
    home: "README.md"
  - dir: "/projects/logic-pro-scripter"
    home: "README.md"
  - dir: "/projects/equal-loudness"
    home: "README.md"
  - dir: "/projects/speaker-loudness-calibration"
    home: "README.md"

  # - dir: "/projects/web-sheet-music-midi"
  #   home: "README.md"


favicon:
  path: /assets/images/musios-logo-black-circle.png

# og_image:
#   output_dir: "assets/images/og"
#   domain: "igor.works"
#   border_bottom:
#     width: 20
#     fill:
#       - "#4285F4"

# og_image:
#   output_dir: "assets/images/og"
#   domain: "musios.app"
#   force: true
#   verbose: true
#   image: "/assets/images/musios-logo-black-circle.png"
#   border_bottom:
#     width: 20
#     fill:
#       - "#F08080"
#   header:
#     font_family: "Roboto, Regular"
#     color: "#933333"
#   content:
#     font_family: "Roboto, Regular"
#     color: "#333333"

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - node_modules
  - _README.md
  - sheet-viewer.html
  - gen-numaxpiano-gp-rigsetup.html

