name: musios.app
title: musios.app
tab_title: "musios.app: tools, scripts and docs for music nerds"
description: A collection of tools for music creators and performers

domain: musios.app
url: "https://musios.app"
baseurl: "/"

lang: en

theme: minima
markdown: kramdown

kramdown:
    syntax_highlighter_opts:
        block:
            line_numbers: true

defaults:
    - scope:
          path: "" # means all files in the project
      values:
          layout: "default"

projects_homes:
    - src: "/projects/gp-support-act/README.md"
    - src: "/projects/web-sheet-music-midi/README.md"
    - src: "/projects/numaxpiano-midi-controller/README.md"
    - src: "/projects/logic-pro-scripter/README.md"
    - src: "/projects/equal-loudness/README.md"
    - src: "/projects/speaker-loudness-calibration/README.md"

author:
    name: Andrew Hunt (musios)
    site: http://musios.app

exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - node_modules
    - _README.md
    - theme.md

plugins:
    - jekyll-sitemap
    - jekyll-feed
    - gemoji
    - kramdown-parser-gfm
