name: musios.app
title: musios.app
tab_title: "musios.app: a collection of tools for music creators and performers"
description: A collection of tools for music creators and performers

domain: musios.app
url: "https://musios.app"
baseurl: "/"

lang: en

theme: minima
markdown: kramdown

kramdown:
    syntax_highlighter_opts:
        block:
            line_numbers: true

defaults:
    - scope:
          path: "" # means all files in the project
      values:
          layout: "default"

projects_homes:
    - dir: "/projects/support-act"
      home: "index.html"
    - dir: "/projects/web-sheet-music-midi"
      home: "README.md"
    - dir: "/projects/numaxpiano-midi-controller"
      home: "README.md"
    - dir: "/projects/logic-pro-scripter"
      home: "README.md"
    - dir: "/projects/equal-loudness"
      home: "README.md"
    - dir: "/projects/speaker-loudness-calibration"
      home: "README.md"

author:
    name: Andrew Hunt (musios)
    site: http://musios.app

exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - node_modules
    - _README.md
    

plugins:
    - jekyll-sitemap
    - jekyll-feed
    - kramdown-parser-gfm
